name: 'LTH - Action Deployer'
description: 'Custom PHP Deployer using GitHub Actions'
inputs:
  args:
    description: 'Parameters for PHP Deployer binary'
    required: true
    default: 'deploy'
  auth_composer:
    description: 'Auth composer token for use with GitHub OAuth'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}
